apiVersion: v1
kind: Service
metadata:
    name: rabbitmqmanagement
spec:
    type: LoadBalancer
    ports:
    - port: 15672 
    selector:
        app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
    name: rabbitmq
spec:
    ports:
    - port: 5672 
    selector:
        app: rabbitmq
